### ISSUE TITLE
1928b Task List

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/Aerial_Flight_Checking#1]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Rescans requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by ahubble** [comment]
Investigate if need to move 1928b 34a image to 1934d?

**Comment by chesleyperry** [comment]
- Based on conversations with Ann, I removed the yellow highlight the row that had a cataloger comment about moving the photo to the 1928d flight.  We agree that this photo belongs with the 1928b's.

- Extent is also highlighted because there are 23 photos and a title page, plus the new geo indexes.  We weren't sure how to note the existence of the title page.

**Comment by chesleyperry** [comment]
Several photos have "unassigned" color profile, needs to be updated to Adobe 1998.

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998
