### ISSUE TITLE
1935 Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#13]
## Index Map Replacement Checklist

- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by ahubble** [comment]
**Extent field:** 
The index is composed of a total of 3 pages:
1 index key
2  index pages
Under the "extent" field in the spreadsheet, should it read: 
144 images + 3 indexes ---> or would it be 1 index? 

**Scale**
Should the scale information be removed from the spreadsheet for the indexes?

**Comment by ahubble** [comment]
Extent field Answer: the index is composed of 3 indexes.

**Comment by chesleyperry** [comment]
Filenames in the "filename" column of the spreadsheet got corrupted somehow and all of the filenames were the same as the first row in the flight.  I copied over the "masterfilenames" and checked against the actual filenames.  It should be accurate now.
