### ISSUE TITLE
1937 Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#14]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
Filenames in the "filename" column of the spreadsheet got corrupted somehow and all of the filenames were the same as the first row in the flight.  I copied over the "masterfilenames" and checked against the actual filenames.  It should be accurate now.
