### ISSUE TITLE
1939e Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#16]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [x] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by afrebert** [comment]
Converted color profile

**Comment by chesleyperry** [comment]
Rename three files, replaced underscores with dashes:

1939e_civ_294_026.tif
1939e_civ_294_027.tif
1939e_civ_294_028.tif

@ahubble:  There is a 4th index file in the folder for this flight, 1939e_civ_index_geo4.jpg.  It's not on the spreadsheet.  Did that get missed or is it an extra file?

**Comment by ahubble** [comment]
@chesleyperry Please add 1939e_civ_index_geo4.jpg to the spreadsheet.
