### ISSUE TITLE
1939f Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#17]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by afrebert** [comment]
Converted color profile to Adobe RGB 1998

**Comment by chesleyperry** [comment]
Six files were missing from the spreadsheet.  They were in the directory on diginit2 and in CONTENTdm.  I looked at the images themselves they the filenames match the labels on the photos. 
I added these files to the spreadsheet and updated the extent to include the 6 extra files.

1939f_civ_284-121.tif
1939f_civ_286-029.tif
1939f_civ_286-030.tif
1939f_civ_286-031.tif
1939f_civ_286-092.tif
1939f_civ_286-093.tif

We should check with Rachel to make sure I've added them to the spreadsheet correctly.


--
