### ISSUE TITLE
1928a Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#2]
## Index Map Replacement Checklist

- [x] New Index Map Titles added to spreadsheet
- [x] New Index Map Filenames added to spreadsheet
- [x] Move New Index Maps into Modified folder in Artifacts2
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Rescans requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
New georectified index maps were in the CONTENTdm jpeg folder so I moved them into the MOD folder

**Comment by chesleyperry** [comment]
One photo, 1928a_09a.tif has an "unassigned" color profile, needs to be updated to Adobe 1998.

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998
