### ISSUE TITLE
1940a Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#20]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [ ] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998

**Comment by chesleyperry** [comment]
Spreadsheet listed files with spaces: "_san lorenzo river_"
Replaced spaces with dashes: "_san-lorenzo-river_"
