### ISSUE TITLE
1943a Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#22]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [ ] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998

**Comment by ahubble** [comment]
Issues:

1. 1943_ddb_2b-157 2.tif is a duplicate image

2. tif files are incorrectly named on artifacts2. They are missing the "a" after 1943 and should be corrected to match the spreadsheet (and Cdm)

Example: 
Artifacts: 1943_ddb_1b-003.tif
Cdm: 1943a_ddb_1b-003.tif

Should I rename files & delete duplicates on Artifacts2 when I see errors? --Ann

**Comment by chesleyperry** [comment]
File renamed 6/4/20 - "added a"
Confirmed 1943_ddb_2b-157 2.tif is a duplicated a deleted
