### ISSUE TITLE
1945a Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#23]
## Index Map Replacement Checklist

- [ ] Index Map Titles added to spreadsheet
- [ ] Index Map Filenames added to spreadsheet
- [ ] Old Index map files moved to superceded directory
- [ ] Old index map removed from the spreadsheet, if appropriate
- [ ] Move new index to modified folder
- [ ] Update extent field

## Filename QA Checklist

- [ ] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [ ] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998

**Comment by ahubble** [comment]
This flight was digitized, but isn't in CDM. See the "[Digitized](https://docs.google.com/spreadsheets/d/1gSpRRlmku0Zp-qNOEvYL9ftwJXo6YFOKPdnQ8D1QxEc/edit#gid=0)" tab on the Aerial Photo Inventory spreadsheet. This flight is highlighted in blue on the spreadsheet, indicating it was digitized by never added to CDM.
