### ISSUE TITLE
1948 Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#24]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [x] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [ ] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
2 files missing from the spreadsheet:

04_24_48_CDF5_1_1.tif
04_24_48_CDF5_1_2.tif
I added the files to the spreadsheet, including "Bolsa Point" as subjectPlace with the geonames URL.  (Bolsa Point was listed in the Buildings and Features field in CONTENTdm).

**Comment by afrebert** [comment]
Color profile is CBMA sRGB
- [x] Change to Adobe RGB 1998
