### ISSUE TITLE
1949 Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#25]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [x] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
Spreadsheet has duplicate entries for 
1949_bux_02f-095.tif
1949_bux_02f-109.tif
and missing entries for 
1949_bux_02f-096.tif
1949_bux_02f-108.tif
Checked CONTENTdm and they are indeed the same image duplicated.  
Replaced the duplicates with the missing filenames.

Files on artifacts with 1949_bux_02 in the filename were missing the "f".  Added the missing letter to match the spreadsheet.

36 of the files on artifacts with 1949_bux_04 in the filename were missing the "f".  Added the missing letter to match the spreadsheet.

**Comment by chesleyperry** [comment]
Spreadsheet was missing file 1949_bux_05f-147.tif but contained duplicate entries for 1949_bux_05f-146.tif
Replaced one of the duplicated 146 files with 147.

**Comment by chesleyperry** [comment]
Spreadsheet was missing file 1949_bux_08f-031.tif but contained duplicate entries for 1949_bux_08f-030.tif
Replaced one of the duplicated 130 files with 131.
Files on artifacts with 1949_bux_08 in the filename were missing the "f". Added the missing letter to match the spreadsheet.

15 files on artifacts starting with "1949_bux_15f-0" had an extra "0" before the final photo number.  Renames files to remove the extra 0.

**Comment by afrebert** [comment]
Epson RGB
- [x] Convert to Adobe RGB 1998
