### ISSUE TITLE
1950 Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#26]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
All 633 files in the spreadsheet listed last set of digits separated with a dash.  Example:
"1950_civ_12g-008.tif".  All files on artifacts have an underscore instead of a dash.
Updated all the filenames on the spreadsheet.

**Comment by afrebert** [comment]
Epson RGB
- [ ] Convert to Adobe RGB 1998
