### ISSUE TITLE
1928c Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#3]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Rescans requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
Several photos have "untagged" color profile, needs to be updated to Adobe 1998.

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998
