### ISSUE TITLE
1956b Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#30]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [x] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
In the spreadsheet, these files all list "7r" in the filename.  The artifacts filenames and the images list "8r" as the image number and filename.  I updated the spreadsheet, replacing 7r with 8r.  
1956b_cja_7r-038.tif
1956b_cja_7r-039.tif
1956b_cja_7r-040.tif
1956b_cja_7r-041.tif
1956b_cja_7r-042.tif
1956b_cja_7r-043.tif
1956b_cja_7r-044.tif
1956b_cja_7r-045.tif
1956b_cja_7r-046.tif
1956b_cja_7r-047.tif
1956b_cja_7r-048.tif
1956b_cja_7r-049.tif
1956b_cja_7r-050.tif
1956b_cja_7r-051.tif
1956b_cja_7r-052.tif
1956b_cja_7r-053.tif
1956b_cja_7r-054.tif
1956b_cja_7r-055.tif
1956b_cja_7r-056.tif
1956b_cja_7r-057.tif

On artifacts, these two files were assigned each other's names:
1956b_cja_8r-038.tif
1956b_cja_8r-039.tif
I swapped the filenames to match the text on the image.

**Comment by afrebert** [comment]
CBMA sRGB
- [ ] Convert to Adobe RGB 1998
