### ISSUE TITLE
1956c Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#31]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [x] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
Filename listed on spreadsheet, not on artifacts2: 1956c_abg_17r-197.tif.  There is a jpg in the 1956c_derivative_cdm folder.  I will put that in the to be scanned column.

File not on spreadsheet or in CONTENTdm: 1956c_abg_17r-186.tif, but it is in artifacts.
I'll add it to the spreadsheet.

**Comment by chesleyperry** [comment]
- [x] Please scan this photo:
Flight 1956c
Photo 17r-197

Filename should be:
1956c_abg_17r-197.tif
Folder:
artifacts2.library.ucsc.edu/diginit2/Aerial_Photos/1956c/1956c_modified

There is a jpeg of the photo and a copy in CONTENTdm but the archival file is missing from the artifacts2 server.

**Comment by chesleyperry** [comment]
@afrebert - I scanned this missing image and added it to diginit2: Aerial_Photos/1956c/1956c_modified/1956c_abg_17r-197.tif.  Could you take a look and see if it needs further processing?

**Comment by afrebert** [comment]
I looked at the images before and after the new scan (1956c_abg_17r-196 and 198) and matched appearance (crop, de-saturate, contrast adjustment)

**Comment by afrebert** [comment]
(Range 1956c_abg_17r-151 to 199 is Adobe RGB 1998, but vast majority is Epson RGB or untagged)

- [x] Convert to Adobe RGB 1998
