### ISSUE TITLE
1961 Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#33]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [x] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
Only one image in the flight.

**Comment by afrebert** [comment]
Changed profile to Adobe RGB (1998)
