### ISSUE TITLE
1928d Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#4]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [ ] Rescans requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by ahubble** [comment]
Issue with 

1928d_113-119_33-2.tif needs resolving

--

**Comment by chesleyperry** [comment]
Several of the rows in the spreadsheet listed the filenames as 1928d_113... rather than 1928d_131...  I updated the spreadsheet to match the filenames.

**Comment by chesleyperry** [comment]
Several photos have an "untagged" color profile, needs to be updated to Adobe 1998.

**Comment by chesleyperry** [comment]
Also updated the spreadsheet to remove the question about cataloger note confusing one photo with a photo in 1928-b.  Removed the note, removed yellow highlight, and removed highlight in the extent cell.

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998
