### ISSUE TITLE
1963k Task List 

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#48]
## Index Map Replacement Checklist

- [ ] Index Map Titles added to spreadsheet
- [ ] Index Map Filenames added to spreadsheet
- [ ] Old Index map files moved to superceded directory
- [ ] Old index map removed from the spreadsheet, if appropriate
- [x] Move new index to modified folder
- [ ] Update extent field

## Filename QA Checklist

- [ ] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [ ] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [ ] Files moved to flat directory on DAMS ingest or artifacts2
