### ISSUE TITLE
1928e Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#5]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Old Index map files moved to superceded directory
- [x] Old index map removed from the spreadsheet, if appropriate

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Rescans requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by chesleyperry** [comment]
One photo, 1928e_131-119_14.tif has Epson color profile.  Needs to be updated to Adobe 1998.

**Comment by afrebert** [comment]
Converted to Adobe RGB 1998

**Comment by ahubble** [comment]
The old index for this flight: 1928d_131-119_index.tif has been superceded by the new version: 1928e_index_geo.jpg. I didn't catch this my first go-round. I will update the spreadsheet and artifacts2 accordingly but wasn't sure what other steps are needed.
