### ISSUE TITLE
1965d Task List

### ISSUE THREAD

**Issue by afrebert** [UCSCLibrary/Aerial_Flight_Checking#53]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Move new index to modified folder
- [x] Update extent field

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check sample images for color profile
- [x] Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2

**Comment by afrebert** [comment]
Epson RGB:

- [ ] Convert to Adobe RGB (1998)

**Comment by afrebert** [comment]
Still shows Epson RGB in Br/Ps, moving back to the "Edit" column

**Comment by afrebert** [comment]
Not all converted

**Comment by afrebert** [comment]
Not all converted 
![Screen Shot 2021-04-06 at 7 38 05 PM](https://user-images.githubusercontent.com/61332016/113802470-a98fa880-970f-11eb-9c18-f88c8fdbcddc.png)

**Comment by scampucsc** [comment]
Angelika,

Some interesting anomalies with these files... I'm curious to know if you are seeing any of them elsewhere in the aerials. 

First, it is worth noting that two of these files are truncated/corrupt for some reason: 1965d_sc_1-152 and 1965d_sc_1-158. Both seem to be corrupted, but openable. I do not remember spotting this last time I looked at them. 

As for color space, it took me 3 tries to get ALL of the files to get the correct color space. I notice in Bridge, that a few of them have EXIF data that is persistent for the Epson 10000 scanner... but most do NOT for whatever reason. I would guess that this flight would have been scanned in its entirety on the same day, or at least divided between two days - but the EXIF data for the Epson seems to appear randomly. I'm wondering if it plays some part in the persistence of the color space not wanting to change?

I have re-uploaded this set. They look OK now to me in both Photoshop AND Bridge, but I'll be curious if you seem the same anomalies. 

Scott
