### ISSUE TITLE
1982f Task List

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/Aerial_Flight_Checking#90]
## Index Map Replacement Checklist

- [x] Index Map Titles added to spreadsheet
- [x] Index Map Filenames added to spreadsheet
- [x] Move new index to modified folder
- [x] Update extent field
- Old Index map files moved to superceded directory, if appropriate
- Old index map removed from the spreadsheet, if appropriate

## Filename QA Checklist

- [x] Photo filenames checked against spreadsheet, correction made
- [x] Check images for color profile
- [x] Convert color profile to Adobe RGB 1998, if needed
- Rescans or image editing requested in ticket comments (if needed)

## File Preparation for Ingest Checklist

- [x] Files moved to flat directory on DAMS ingest or artifacts2
